### ISSUE TITLE
Time not formatted to correct time zone in VolunteerReportHours shift listbox

### ISSUE THREAD

**Issue by davidhabib** [davidhabib/Volunteers-for-Salesforce#123]
hub thread with info: https://powerofus.force.com/0D58000001nIKdT

**Comment by davidhabib** [comment]
included in version 3.76

**Comment by KathrynLee** [comment]
David,

I know you just updated this, but when should we expect version 3.76 to be available. 

Thanks.

**Comment by davidhabib** [comment]
by end of the weekend I hope to do a push upgrade to all production orgs.

**Comment by KathrynLee** [comment]
David,

Awesome news! Thank you so much!

 Kathryn Lee  Quality Assurance Manager
    Direct:  510-768-3156
   Email: klee@cceb.org
 Website: http://www.cceb.org
 Address: 433 Jefferson St., Oakland CA 94607

<https://www.facebook.com/CatholicCharitiesoftheEastBay?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/cceb?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/company/catholic-charities-of-the-east-bay?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 "Be the Hands of Hope" Catholic Charities Annual Appeal
<http://www.cceb.org/get-involved/donate/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
