### ISSUE TITLE
support filtering by parent campaign in Sites pages

### ISSUE THREAD

**Issue by davidhabib** [davidhabib/Volunteers-for-Salesforce#141]
hub request: https://powerofus.force.com/0D580000025Iexy

the JobListing and Calendar page both support filtering by a single campaignId.  This request would be to allow that campaignId be a parent campaign, and then include all Jobs/Shifts from child volunteer campaigns of the passed in campaign.

**Comment by cdcarter** [comment]
Would it be preferred to have an additional query string param of "includeHierarchy=true" when a campaignId is set?

**Comment by sgjudd** [comment]
I like the idea of a query parameter - this is one of the enhancements to V4S that is on my list if I kind carve out the time to dig in.

**Comment by cdcarter** [comment]
@sgjudd I'm digging in right now at https://github.com/cdcarter/Volunteers-for-Salesforce/tree/campaignhierarchy. Hope to have a patch in this weekend.

**Comment by cdcarter** [comment]
Pull request above offers the desired behavior in JobListing pages as an optional boolean.

Inside of that commit history is an implementation for JobCalendar too, but I then removed it. I don't know well enough how Javascript Remoting and everything else that has that Calendar wired up quite works. Today, I couldn't reason about how to make it a non-required option, so I didn't change existing behavior. I will try and investigate further but could use some guidance!

**Comment by davidhabib** [comment]
will be included in version 3.76.  I also added support for ShowCampaignHierarchy on the JobCalendar page, and added additional tests code for all of the Sites pages supporting this URL parameter.
