### ISSUE TITLE
Option to modify/disable Campaign-Create Statuses trigger

### ISSUE THREAD

**Issue by Zosoled** [davidhabib/Volunteers-for-Salesforce#152]
While creating these statuses by default for new campaigns is useful, this trigger prevents cloned campaigns from carrying over the original campaign's Member Status values.

**Comment by davidhabib** [comment]
are you saying this happens with all campaign record types, or just Volunteer Campaigns?

**Comment by Zosoled** [comment]
This only happens with Volunteer Campaigns, because of this trigger I'm assuming: Volunteers-for-Salesforce/src/triggers/VOL_Campaign_CreateStatuses.trigger

The trigger inserts the hard-coded Campaign Member Statuses then deletes the original ones.

**Comment by davidhabib** [comment]
V4S is going to overwrite any campaign member statuses with the values it uses when Hours get updated.  That's why on the New trigger, it removes the default ones and adds its special ones.   I don't know how we can detect that the insert is actually a clone.  Also don't understand the use case of or side affect of not having the V4S statuses and leaving the default ones in.

**Comment by Zosoled** [comment]
We have a client who would like to customize the member statuses of certain volunteer campaigns, to fit their own processes better. If they're customized, they'd like to be able to clone them to future campaigns. Would you suggest that the values not be customized at all?

**Comment by davidhabib** [comment]
yep.  V4S will overwrite the statuses with Active when a Volunteer Hours record is saved.  They could always add their own custom fields on CampaignMembers instead to track additional info.

**Comment by TGMarcovecchio** [comment]
All:

Been following this conversation. Agreed. It would be nice if Vol did not
overwrite campaign member status as it currently does but rather allowed
for a custom mapping or use of preexisting values on the referenced
campaign. We have used other methods as a work around ... But it would be
nice to avoid work around.
