### ISSUE TITLE
Cloning campaigns does not consider Campaign Member record type

### ISSUE THREAD

**Issue by Zosoled** [davidhabib/Volunteers-for-Salesforce#153]
Low priority I'm sure, but...
Consider a volunteer campaign created before any Campaign Member record types exist. Subsequently, CM record types are established, but the existing campaign is not updated to reflect this. Cloning that campaign will fail to run [VOL_Campaign_CreateStatuses](Volunteers-for-Salesforce/src/triggers/VOL_Campaign_CreateStatuses.trigger) properly, and no Campaign Member Statuses are created.

**Comment by davidhabib** [comment]
There is nothing V4S can do here.  It only recognizes Campaigns that have the Volunteers Campaign record type, so there is no way to know the cloned campaign should be a Volunteers Campaign.
