### ISSUE TITLE
Display user friendly error messages for Validation Rule errors

### ISSUE THREAD

**Issue by derekdanderson** [davidhabib/Volunteers-for-Salesforce#174]
If we add a Validation Rule to prevent the creation of Volunteer Hours for inactive Contacts, the PersonalSiteJobListing page throws an unfriendly error message containing the text of the Validation Rule Error message:

Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Only Active Volunteers who have competed orientation can register for Volunteer Jobs online. Please contact the Manager of Volunteers: volunteers@lakeviewpantry.org: []

![screen shot 2016-01-26 at 11 53 15 am](https://cloud.githubusercontent.com/assets/1254526/12589451/6dd63f26-c423-11e5-90dc-6486b2ebc947.png)

You can return only the Validation Rule error text by handling the DMLException errors in the VOL_CTRL_VolunteersJobListingFS class.  

} catch (DMLException e){
    //Added check for FIELD_CUSTOM_VALIDATION_EXCEPTION to return user friendly error.
    String errorMsg = e.getMessage();
    if(errorMsg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')){
        errorMsg = errorMsg.substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ', ': ');
    }
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,errorMsg));
}

**Comment by cdcarter** [comment]
We should probably do something similar in VOL_CTRL_VolunteersReportHours, and probably VOL_CTRL_VolunteersSignupFS as well.

**Comment by davidhabib** [comment]
yep!

**Comment by derekdanderson** [comment]
Awesome!
