### ISSUE TITLE
First Name, Last Name and Email fields should be read only only in the Volunteer popup because these fields are used to match the Contact record in Salesforce.

### ISSUE THREAD

**Issue by mnimon** [davidhabib/Volunteers-for-Salesforce#176]
![https___marthanimo-lakeviewpantry_cs24_force_com_gw_volunteers__personalsitejoblisting_calendar_1_volunteershiftid_a0719000004shqpaay_jobid_a0619000004ibaaaas_dtmonthfilter_2016-1-26_8_30_0_language_en-us_nmonthstoshow_1](https://cloud.githubusercontent.com/assets/16903962/12595161/64e8aad6-c43f-11e5-8ea4-2296bf07176b.jpg)

**Comment by davidhabib** [comment]
#177 deals with the need to make these read only when in the Personal Site.  But when used as general pages on a website, this is a scenario V4S has been asked to support; allow a person to signup up multiple people, one at a time.  So I don't think we'd make them read only in the non-Personal Site scenario.
