### ISSUE TITLE
FullCalendar Out of Date

### ISSUE THREAD

**Issue by claico** [davidhabib/Volunteers-for-Salesforce#179]
The version of FullCalendar in the package is 1.5.2. This is over two years old. The current version is 2.6.0, release about 4 weeks ago. The big different in version 2.0 and beyond is the introduction of [moment.js](http://momentjs.com/), an improved technique for handling time/date fields.

Also, I would like to see the package be broken into components that there is not a different static resource for every package's version of jQuery, moment.js, FullCalendar.

Finally, I would like to be able to make use of FullCalendar with my saleforce org for other objects that are not Volunteers. Maybe a non-managed version of the calendar parts that could be used to develop other calendar view.

Judi told be to contact you.

**Comment by davidhabib** [comment]
V4S is deployed to over 4000 organizations, so updating its code cannot be taken lightly.  What drives the decision on what calendar component is in the code is whether it meets the requirements for V4S.  I believe it currently does, and am not aware of any new V4S features would be enabled by moving to a later version.  If there are new V4S features that get added in the future that require a newer calendar component, then that decision will be made at that time.

As for breaking the package into components, that is beyond the goal and purpose of V4S.  V4S is intended to provide a volunteer management system.  It's goal is not to serve as a development platform for additional work.  Granted, it is open source and several classes are global to allow those who want to create their own version of Sites pages possible.

Finally, if you want to use FullCalendar for your other purposes go for it. There is nothing in V4S from preventing you from adding your own static resource of this library.
