### ISSUE TITLE
Off-site signup

### ISSUE THREAD

**Issue by sgjudd** [davidhabib/Volunteers-for-Salesforce#186]
We have cases where we list volunteer opportunities for outside organizations where the sign-up would occur at the organization's website, instead of through Salesforce. Need to have a method to provide outside URL on volunteer job and have sign-up button link to that URL.

**Comment by jlantz** [comment]
Included in beta release 3.88 (Beta 7)

**Comment by jlantz** [comment]
Included in production release rel/3.88
