### ISSUE TITLE
Comment field on VolunteersReportHours

### ISSUE THREAD

**Issue by sgjudd** [davidhabib/Volunteers-for-Salesforce#188]
For GW_Volunteers__VolunteersReportHours - include comments field so volunteers can add information to hours report

**Comment by davidhabib** [comment]
this should be supported by #94 which is adding field set support on VolunteerHours to the VolunteerReportHours page.

**Comment by jlantz** [comment]
Included in beta release 3.88 (Beta 7)

**Comment by jlantz** [comment]
Included in production release rel/3.88
