### ISSUE TITLE
Error while installing the repository

### ISSUE THREAD

**Issue by apoorvamathur12** [davidhabib/Volunteers-for-Salesforce#204]
Hi,
I'm new in github. While installing the package I'm getting this error:

"package.xml:The specified package namespace: GW_Volunteers does not match the namespace for the server:"

Can you please help me to figure out what does it mean exactly? What do I need to do to resolve the problem?

**Comment by davidhabib** [comment]
sounds like you are trying to save all the unmanaged code to your org?  you need to fixup any hardcoded references to GW_Volunteers to use no namespace. 

In the future, please post questions like these on the Salesforce Foundation's Power of Us Hub, in the Volunteers for Salesforce App group at https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjjX

The Hub is an online community of users and consultants who help each other with questions.  I also monitor the group and will chime in if needed.

**Comment by apoorvamathur12** [comment]
Hi David,
Thanks a lot for your response!
I'm really new to understand how I can fixup the hardcoded references of
GW_Volunteers to use no namespace. Please help me here!
Could you point me towards some document or video anything through which I
could learn how to fix this issue. Your response would really mean a lot!

Thanks and Regards:
Apoorva Mathur
