### ISSUE TITLE
Add fieldset on Volunteer Hours to the VolunteersReportHours Sites page

### ISSUE THREAD

**Issue by davidhabib** [davidhabib/Volunteers-for-Salesforce#94]
From Zach Munsey (Hopelink) on the HUB:

Is it possible to add Volunteer Shift custom fields to the Report Hours page? I am able to add Contacts fields to it through the VolunteersReportHours Field Set, but would like volunteers to be able to report on hours and a few custom fields added to the Volunteer Hours object.

Our end goal would be to have volunteers update their hours along with items like number of brochures distributed, type of assistance given, number of clients helped, etc.

**Comment by chigginbothamBGCIndy** [comment]
I would like to be able to add Campaign to the Report Hours page and use the Campaign selected to limit the list of Volunteer Jobs that are visible. Because I have jobs at multiple sites, an unfiltered list of jobs could get very long. (The list could easily grow to 50 active jobs.)

**Comment by davidhabib** [comment]
added a separate feature request #173 for chigginbothamBGCIndy's comment.

**Comment by KevinPhaup** [comment]
yes - I'd love to be able to restrict jobs on the report hours page using a parameter - either by jobid, or could happily restrict by campaign. We want board members to report their volunteer hours, and they have issues picking from the long list of jobs used for other volunteer tracking purposes. :)

**Comment by jlantz** [comment]
Included in beta release 3.88 (Beta 7)

**Comment by jlantz** [comment]
Included in production release rel/3.88
